dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
  - maintenance-1.1
before_install:
- mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/nbnuk/travis-build-configuration/master/travis_maven_settings.xml
- sudo mkdir -p /data/lucene; sudo wget -O /data/lucene/namematching-20210811-3.tgz
  https://archives.ala.org.au/archives/nameindexes/20210811-3/namematching-20210811-3.tgz
- cd /data/lucene
- sudo tar zxvf namematching-20210811-3.tgz
- sudo ln -s namematching-20210811-3 namematching
- ls -laF
- sudo mkdir -p /data/sds
- sudo wget -O /data/sds/sds-test-config.tgz https://archives.ala.org.au/archives/test/sds-test-config.tgz
- cd /data/sds
- sudo tar xvzf sds-test-config.tgz
- cd $TRAVIS_BUILD_DIR
- echo TRAVIS_PULL_REQUEST = ${TRAVIS_PULL_REQUEST}
script:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then mvn -P travis clean install deploy;
  else mvn -P travis clean install; fi
env:
  global:
  - secure: D6StJFSB1vyQz6aaHO0o0at2FPXzmY91WGM6doCA1+HV/QNx6jiPEHm7EyCX4YXUgLo4B/nQQJOoiGgqt5smYvhwq37oIZZOzzG5TCbgNgQEjhw+ARo1xDs98nK4vGx4u5/lz5uHPK8lgWINoVt2IvxTWymYdy02pQeg9x3jx1OZJEL7kXqu6cSGjn4p8N2BztjVtjIp886Q6DFRHL+s6s8FqfOyWpQsZYb6cwpPlBIHBDuvzfAsZXCYW7qaa4pXa3WOFRU2yoOD5LydRlfrRkde3Op6bOeToxf5aSDgDuL4pCr4cnX+02OC3MuGzFmO3ZXRf3rkOKiehUWMvvWHjTNGqvMffcMvZEGm9ttxfeCSlnbPwxKp1xp+u72GY7seAhPog7ZVbhLb31CS7VA7Yc5npr4e5lfJK7ahoSwGt9nRwOR0QpV3U0jAqms+ZmR5XKnWiV5jc+7ByfoM4ujnLdVmQjl5vWit+S/OPIXaEMXeDwWwI0fscw7fpDMOtMHu42SE+dl1OUI/lyNFj3XMgwIPPvuO2fkXzl+RTcHDkcI4gCH5ctnyw8WAUGbZmGNmwXN5IneLsMrJwqi5ufI/Rwl0RDe73WWmATNNCVi/Ybjzql4Cpxctmt5jlGSdrP/GS2RI3zKCz0tTxSSjr9/6TITTHY0NdZ0nZhkZGxsn/r8=
  - secure: DsOZPhtUPKLz0p+fQiEsm0I5q09/jkjaerrY+Lbb8AWA+LO9W3ITCqiWcmXdq+q6n/79tK3ctFQpqHAFqWaOkZgDfBuVYbP0jQ+8CqdRJifftxu48GrjEAJJOiO/E/fepmLeCx/JOQ0dlQKKVc81JlptHVE5buQHglmS4d5kBuLBOk2q4Dhihazjiv5l2Pk8QwQSe8xbG0vetuGVS9qckowM5XgCkEW/JkrbZLKDu9IIAjE2NO0I1xP38dcfItRIiNj4C9izl2cqP6NXzOVyY0t4ZME5NXBmniCd7q4vf+J23v4Cet6BW8MUcOKUc5NFA31vW6bpjp79Kk10zX+rTBMuJVyz0L5cZSgbP8Rqd0h6dvCBrZJVZ6EIJft74jcSbSw7HlEBzWB8EhEBL7anrxY9VSOOff2/aQZg3ZOBys5U3YWgy85w78MsmS2UPZr1Xw6QXE5eTrB+VSS0Ymo1wnIDcAPfuYFTd9cnwAghnweecs2svefkAMh3ZDaiMPpxUXNj7eVRo+9wu5ft+3m1BLiIhdXDMKrYiSl+Izh6e/DpaF/3ItH44j0tdHWKHtSD0llmsULe8Wg5SP1kLLa8WhtLfMpXWmo0BYoNaBM0eUAiVYWkRptRNpYOZeJKQMOm6RPYGrg0Awb9A1apRztwe2kqDf0Nd01Efn4c+ERIzw0=
